### ISSUE TITLE
[Bug] Taches cochée / Enhancement : ajout suppression de taches

### ISSUE THREAD

**Issue by benjbubu** [LoucIsZbib/BaraTasks#11]
Suite à la MAJ de Louc pour les ajouts de taches, si une tache est cochée car finie, apres le full refresh (ctrl+F5) la tâche n'est plus cochée.

A revoir + ajout suppression de taches définitive

**Comment by benjbubu** [comment]
Corrigée dans 6f340f3 (pour le refresh)

Manque l'ajout de la suppression définitive de la tache

**Comment by LoucIsZbib** [comment]
on va le mettre dans une autre issue ;:)
