### ISSUE TITLE
rendre les liens cliquables

### ISSUE THREAD

**Issue by LoucIsZbib** [LoucIsZbib/BaraTasks#14]

**Comment by benjbubu** [comment]
Quelques idées : 
https://docs.angularjs.org/api/ngSanitize/filter/linky

http://oskarhane.com/angular-js-filter-to-make-urls-in-text-clickable/

**Comment by LoucIsZbib** [comment]
Problème : ng-model n'est pas "filtrable", il faut créer une directive custom (ng-model-linky) ou trouver un workaround
piste directive custom : http://jsfiddle.net/k7Lq0rns/1/

**Comment by LoucIsZbib** [comment]
piste : 

If you want to have the filter within the html and not in ng-model, this is an alternative:

input type="text" ng-model="var" value="var|currency" /

You can add it to value attribute.

**Comment by LoucIsZbib** [comment]
bon, on ne peut pas avoir un champ input et une url cliquable dedans.
Soit on laisse tomber la fonction, soit on crée un truc qui simule une balise <input /> mais qui n'est pas une. La question est : comment ?

**Comment by LoucIsZbib** [comment]
jouer avec un `<span ng-hide="inEdition" ng-click="inEdition = true"> et un <input ng-show="inEdition" ng-change="inEdition = false" />` ?

**Comment by LoucIsZbib** [comment]
tentative dans une branche à part : cf5ad42c009388265f87d17c5db265e2e160c8d3

**Comment by benjbubu** [comment]
Test du dernier commit : toutes les fonctionnalités sont là sans erreur de console. 

Test en ajoutant link:'_blank' pour ouvrir le lien dans un nouvel onglet : le formatage disparait au clic il faut rééditer la tache pour que le parse se refasse mais sinon tout a l'air de fonctionner

**Comment by benjbubu** [comment]
https://jsfiddle.net/tridip/muz887hu/1/ <- Bouton edition avec autofocus
 Pour l'id de la tache en ng-repeat et pour éviter le problème de doublon : listid_taskid
