### ISSUE TITLE
[Bug]Actualisation du diffFromToday ? 

### ISSUE THREAD

**Issue by benjbubu** [LoucIsZbib/BaraTasks#20]
Test réalisé sous : IE sur ordinateur différent / Chrome sous Android

Explication : 
-> Le 17/10/2017 je crée une tache avec date d'échéance au 17/10/2017. Le diffFromToday est donc égal à 0.
Je crée  une seconde tâche également avec date d'échéance au 20/10/2017. Le diffFromToday est donc égal à 3.

-> Le 18/10/2017 au lancement du site le diffFromToday n'a pas été actualisé. Il reste toujours à 0 pour la tache avec due date au 17 et 3 pour la due date au 20 alors que la variable devrait être respectivement -1 et 2. 

J'ai testé ctrl+F5 et swap de listes, rien n'y change.

**Comment by LoucIsZbib** [comment]
ça marche, {{ }} n'est pas nécessaire quand la variable est dynamique (j'ai lu ça qque part)
