### ISSUE TITLE
[A TESTER PUIS CLOTURE]les comparaisons de date (diff) tiennent comptent de l'heure

### ISSUE THREAD

**Issue by LoucIsZbib** [LoucIsZbib/BaraTasks#21]
donc si je met une échéance le 19 et que nous sommes le 18 20h, il n'y a pas 1 jour de différence, mais seulement qques heures...
piste : manipuler les dates au format objet momentjs pour n'avoir que la date : idée = https://stackoverflow.com/questions/26712990/momentjs-day-diff-dates-only-excluding-time

**Comment by benjbubu** [comment]
Test du startof. Aucun erreur JS dans le developper tool. 
Suppression de Math.ceil étant donné que le startof permet des chiffres ronds (confirmation via le debug)

52e1d45
