### ISSUE TITLE
[Bug]Suppression des taches barrées NOK si plusieurs listes existantes

### ISSUE THREAD

**Issue by benjbubu** [LoucIsZbib/BaraTasks#23]
Lorsqu'on clique sur le bouton megadone pour supprimer toutes les taches barrées j'ai l'erreur suivante 
angular.min.js:114 TypeError: Cannot read property 'completed' of undefined

Le bug semble survenir uniquement lorsque plusieurs listes sont crées

**Comment by LoucIsZbib** [comment]
résolu par le commit 6a7c90c9b292ed7dd6abe8cffeaa17307411f6d7 , on transmet désormais la liste et on la parcourt à l'envers
