### ISSUE TITLE
Ajouter le nombre de taches non complétées à coté du nom des listes

### ISSUE THREAD

**Issue by benjbubu** [LoucIsZbib/BaraTasks#29]
A voir la faisabilité mais il serait pratique d'avoir en un coup d'oeil le nombre de tâches sans le statut item:completed. Lorsque l'on a plusieurs listes à gérer ca permet tout de suite de savoir là où il reste le plus de tâches

**Comment by benjbubu** [comment]
Premier commit qui fonctionne e871f63 

Cependant il compte l'intégralité des tâches (barrées ou non)

Voir pour une fonction :  
todoApp.filter('uncompleted', function() {
    return function(input) {
            var nombre = 0;
            if (input != undefined) {
                for val in input {
                    if !input.completed {
                        nombre++:
                    }        
                }
            }

**Comment by LoucIsZbib** [comment]
C'est fait d5c79b0bcfc12f05646273723040e48586ac3101
